script: train_scoring.py
hyperparameters:
  epochs: 30
  batch_size: 30
inputs:
  covid_scoring_metadata_dir: s3://qtr-ml-projects/prj-covid-scoring/dataset/metadata/covid_scoring_metadata.csv
  source_ds_dir: s3://qtr-ml-projects/prj-covid-scoring/dataset/covid_scoring/COVID-19 scoring_converted_annotations/
dependencies:
   - tools
   - requirements.txt
